In [2]:
import pandas as pd

df = pd.read_csv("/content/pisa_chile_evolucion_2000_2025_limpia.csv")

df.head()

,anio,puntaje_lectura,bajo_nivel_2_pct,nivel_5_o_superior_pct,desviacion_estandar,rango_interdecil
0,2000,409.55678,48.16997,0.50474,89.85703,232.16000
1,2006,442.09135,36.25924,3.52718,103.23710,265.04238
2,2009,449.36961,30.56255,1.27517,82.66453,213.66400
3,2012,441.39816,33.01533,0.60131,77.93579,201.75256
4,2015,458.57088,28.38462,2.26497,88.14471,229.45450

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   anio                    8 non-null      int64
 1   puntaje_lectura         8 non-null      float64
 2   bajo_nivel_2_pct        8 non-null      float64
 3   nivel_5_o_superior_pct  8 non-null      float64
 4   desviacion_estandar     8 non-null      float64
 5   rango_interdecil        8 non-null      float64
dtypes: float64(5), int64(1)
memory usage: 516.0 bytes

In [4]:
df.isnull().sum()

anio                      0
puntaje_lectura           0
bajo_nivel_2_pct          0
nivel_5_o_superior_pct    0
desviacion_estandar       0
rango_interdecil          0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
evolucion = df.sort_values("anio")

evolucion

,anio,puntaje_lectura,bajo_nivel_2_pct,nivel_5_o_superior_pct,desviacion_estandar,rango_interdecil
0,2000,409.55678,48.16997,0.50474,89.85703,232.16000
1,2006,442.09135,36.25924,3.52718,103.23710,265.04238
2,2009,449.36961,30.56255,1.27517,82.66453,213.66400
3,2012,441.39816,33.01533,0.60131,77.93579,201.75256
4,2015,458.57088,28.38462,2.26497,88.14471,229.45450
5,2018,452.27255,31.72095,2.59417,92.01774,240.59900
6,2022,447.97896,33.72691,2.48577,93.27371,239.06020
7,2025,435.65582,38.17916,1.77870,93.51497,243.68562

In [8]:
mayor_puntaje = df.loc[df["puntaje_lectura"].idxmax()]
menor_puntaje = df.loc[df["puntaje_lectura"].idxmin()]

print("Ciclo con mayor puntaje:")
print(mayor_puntaje[["anio", "puntaje_lectura"]])

print("\nCiclo con menor puntaje:")
print(menor_puntaje[["anio", "puntaje_lectura"]])

Ciclo con mayor puntaje:
anio               2015.00000
puntaje_lectura     458.57088
Name: 4, dtype: float64

Ciclo con menor puntaje:
anio               2000.00000
puntaje_lectura     409.55678
Name: 0, dtype: float64

In [9]:
evolucion["cambio_puntaje"] = evolucion["puntaje_lectura"].diff()

evolucion[["anio", "puntaje_lectura", "cambio_puntaje"]]

   anio  puntaje_lectura  cambio_puntaje
0  2000        409.55678             NaN
1  2006        442.09135        32.53457
2  2009        449.36961         7.27826
3  2012        441.39816        -7.97145
4  2015        458.57088        17.17272
5  2018        452.27255        -6.29833
6  2022        447.97896        -4.29359
7  2025        435.65582       -12.32314

In [10]:
evolucion[
    ["anio", "bajo_nivel_2_pct"]
].sort_values("anio")

   anio  bajo_nivel_2_pct
0  2000          48.16997
1  2006          36.25924
2  2009          30.56255
3  2012          33.01533
4  2015          28.38462
5  2018          31.72095
6  2022          33.72691
7  2025          38.17916

In [11]:
evolucion[
    ["anio", "desviacion_estandar", "rango_interdecil"]
].sort_values("anio")

   anio  desviacion_estandar  rango_interdecil
0  2000             89.85703         232.16000
1  2006            103.23710         265.04238
2  2009             82.66453         213.66400
3  2012             77.93579         201.75256
4  2015             88.14471         229.45450
5  2018             92.01774         240.59900
6  2022             93.27371         239.06020
7  2025             93.51497         243.68562